import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      ".turbo/**",
      "playwright-report/**",
      "test-results/**",
      "next-env.d.ts", // auto-generated by Next.js, must not be edited
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
